# Generated by Django 2.0.7 on 2018-07-18 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
				name = 'Album',
				fields = [
					('id',
					 models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
					('poster', models.ImageField(null = True, upload_to = '')),
					('name', models.CharField(max_length = 100)),
					('introduction', models.TextField()),
					('release_time', models.DateField(null = True)),
				],
		),
		migrations.CreateModel(
				name = 'Comment',
				fields = [
					('id',
					 models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
					('title', models.CharField(max_length = 100, null = True)),
					('text', models.TextField()),
				],
		),
		migrations.CreateModel(
				name = 'Music',
				fields = [
					('id',
					 models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
					('name', models.CharField(max_length = 100)),
					('release_time', models.DateField(null = True)),
					('url_address', models.URLField()),
					('play_counts', models.IntegerField(default = 0)),
					('delete_status', models.NullBooleanField()),
					('free_status', models.NullBooleanField()),
					('price', models.FloatField(max_length = 3)),
					('introduction', models.CharField(max_length = 200, null = True)),
					('album', models.ForeignKey(null = True, on_delete = django.db.models.deletion.SET_NULL,
					                            related_name = 'music_belong_to_album',
					                            related_query_name = 'album_query_by_music', to = 'user_app.Album')),
				],
		),
		migrations.CreateModel(
				name = 'MusicSheet',
				fields = [
					('id',
					 models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
					('name', models.CharField(max_length = 200)),
					('create_time', models.DateTimeField(null = True)),
					('collect_count', models.IntegerField()),
					('icon_path', models.ImageField(null = True, upload_to = '')),
				],
		),
		migrations.CreateModel(
				name = 'Singer',
				fields = [
					('id',
					 models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
					('name', models.CharField(max_length = 100)),
					('image', models.ImageField(null = True, upload_to = '')),
					('introduction', models.TextField()),
				],
		),
		migrations.CreateModel(
				name = 'User',
				fields = [
					('id',
					 models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
					('name', models.CharField(max_length = 100, unique = True)),
					('sex', models.CharField(default = 'male', max_length = 5)),
					('age', models.IntegerField(null = True)),
					('password', models.CharField(max_length = 200)),
					('email', models.EmailField(max_length = 254)),
					('phone', models.CharField(max_length = 20, null = True)),
					('introduction', models.TextField(null = True)),
					('icon', models.ImageField(upload_to = '')),
					('last_login_time', models.DateTimeField(null = True)),
					('token', models.CharField(max_length = 200, null = True)),
					('music', models.ManyToManyField(to = 'user_app.Music')),
					('music_sheet', models.ManyToManyField(to = 'user_app.MusicSheet')),
				],
		),
		migrations.AddField(
				model_name = 'music',
				name = 'music_bind_singer',
				field = models.ForeignKey(null = True, on_delete = django.db.models.deletion.SET_NULL,
				                          related_name = 'music_belong_to_singer',
				                          related_query_name = 'singer_query_by_music', to = 'user_app.Singer'),
		),
		migrations.AddField(
				model_name = 'music',
				name = 'music_sheet',
				field = models.ManyToManyField(to = 'user_app.MusicSheet'),
		),
		migrations.AddField(
				model_name = 'comment',
				name = 'music',
				field = models.ForeignKey(null = True, on_delete = django.db.models.deletion.SET_NULL,
				                          related_name = 'comment', to = 'user_app.Music'),
		),
		migrations.AddField(
				model_name = 'comment',
				name = 'music_sheet',
				field = models.ForeignKey(null = True, on_delete = django.db.models.deletion.SET_NULL,
				                          related_name = 'comment', to = 'user_app.MusicSheet'),
		),
		migrations.AddField(
				model_name = 'album',
				name = 'singer',
				field = models.ForeignKey(null = True, on_delete = django.db.models.deletion.SET_NULL,
				                          related_name = 'album_belong_to_singer',
				                          related_query_name = 'album_query_by_singer', to = 'user_app.Singer'),
		),
	]